name: submodule

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cryostat-submodule:
    if: ${{ github.repository_owner == 'cryostatio' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        repository: cryostatio/cryostat
        token: "${{ secrets.SUBMODULE_TOKEN }}"
        ref: "${{ github.ref_name }}"
    - name: Check remote cryostat submodule branch
      run: |
        remote_branch="$(git config --get -f .gitmodules submodule."src/main/webui".branch)"
        if [[ "$remote_branch" != "${{ github.ref_name }}" ]]; then
          printf "Expected remote branch %s, found branch %s\n" "${{ github.ref_name }}" "$remote_branch" >&2
          exit 1
        fi
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Update submodule to latest commit
      run: |
        git submodule update --init
        git submodule update --remote
    - uses: actions/github-script@v8
      id: get_issue_number
      with:
        script: |
          if (context.issue.number) {
            // Return issue number if present
            return context.issue.number;
          } else {
            // Otherwise return issue number from commit
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].number;
          }
        result-encoding: string
    - name: Commit
      env:
        GH_TOKEN: ${{ secrets.SUBMODULE_TOKEN }}
      run: |
        git add --all
        git_hash="$(git rev-parse --short :src/main/webui)"
        title="build(webui): update submodule to ${git_hash}"
        body="see cryostatio/cryostat-web#${{ steps.get_issue_number.outputs.result }}"
        branch="ci-update-${git_hash}"
        git commit -S -m "${title}" -m "${body}"
        echo "PR_TITLE=${title}" >> "$GITHUB_ENV"
        echo "PR_BRANCH=${branch}" >> "$GITHUB_ENV"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        title: ${{ env.PR_TITLE }}
        branch: ${{ env.PR_BRANCH }}
        branch-token: ${{ secrets.SUBMODULE_TOKEN }}
        push-to-fork: cryostat-bot/cryostat
        maintainer-can-modify: false
        delete-branch: true

  update-console-plugin-submodule:
    if: ${{ github.repository_owner == 'cryostatio' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        repository: cryostatio/cryostat-openshift-console-plugin
        token: "${{ secrets.SUBMODULE_TOKEN }}"
        ref: "${{ github.ref_name }}"
    - name: Check remote cryostat submodule branch
      run: |
        remote_branch="$(git config --get -f .gitmodules submodule."src/cryostat-web".branch)"
        if [[ "$remote_branch" != "${{ github.ref_name }}" ]]; then
          printf "Expected remote branch %s, found branch %s\n" "${{ github.ref_name }}" "$remote_branch" >&2
          exit 1
        fi
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Update submodule to latest commit
      run: |
        git submodule update --init
        git submodule update --remote
    - uses: actions/github-script@v8
      id: get_issue_number
      with:
        script: |
          if (context.issue.number) {
            // Return issue number if present
            return context.issue.number;
          } else {
            // Otherwise return issue number from commit
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].number;
          }
        result-encoding: string
    - name: Commit
      env:
        GH_TOKEN: ${{ secrets.SUBMODULE_TOKEN }}
      run: |
        git add --all
        git_hash="$(git rev-parse --short :src/cryostat-web)"
        title="build(webui): update submodule to ${git_hash}"
        body="see cryostatio/cryostat-web#${{ steps.get_issue_number.outputs.result }}"
        branch="ci-update-${git_hash}"
        git commit -S -m "${title}" -m "${body}"
        echo "PR_TITLE=${title}" >> "$GITHUB_ENV"
        echo "PR_BRANCH=${branch}" >> "$GITHUB_ENV"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        title: ${{ env.PR_TITLE }}
        branch: ${{ env.PR_BRANCH }}
        branch-token: ${{ secrets.SUBMODULE_TOKEN }}
        push-to-fork: cryostat-bot/cryostat-openshift-console-plugin
        maintainer-can-modify: false
        delete-branch: true
