name: submodule

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

defaults:
  run:
    shell: bash

jobs:
  update-submodule:
    if: ${{ github.repository_owner == 'cryostatio' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: cryostatio/cryostat
        token: "${{ secrets.SUBMODULE_TOKEN }}"
        ref: "${{ github.ref_name }}"
    - name: Check remote submodule branch
      run: |
        remote_branch="$(git config --get -f .gitmodules submodule.web-client.branch)"
        if [[ "$remote_branch" != "${{ github.ref_name }}" ]]; then
          printf "Expected remote branch %s, found branch %s\n" "${{ github.ref_name }}" "$remote_branch" >&2
          exit 1
        fi
    - name: Update submodule to latest commit
      run: |
        git submodule update --init
        git submodule update --remote
    - name: Commit and push submodule
      # User info comes from: https://github.community/t/github-actions-bot-email-address/17204/5
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git config commit.gpgsign true
        git add --all
        git_hash="$(git rev-parse --short :web-client)"
        git commit -m "build(web-client): update submodule to $git_hash" || echo "No changes to commit"
        git push
