name: submodule

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

defaults:
  run:
    shell: bash

jobs:
  update-cryostat-submodule:
    if: ${{ github.repository_owner == 'cryostatio' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        repository: cryostatio/cryostat
        token: "${{ secrets.SUBMODULE_TOKEN }}"
        ref: "${{ github.ref_name }}"
    - name: Check remote cryostat submodule branch
      run: |
        remote_branch="$(git config --get -f .gitmodules submodule."src/main/webui".branch)"
        if [[ "$remote_branch" != "${{ github.ref_name }}" ]]; then
          printf "Expected remote branch %s, found branch %s\n" "${{ github.ref_name }}" "$remote_branch" >&2
          exit 1
        fi
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Update submodule to latest commit
      run: |
        git submodule update --init
        git submodule update --remote
    - name: Commit and push submodule
      run: |
        git add --all
        git_hash="$(git rev-parse --short :src/main/webui)"
        export msg="build(webui): update submodule to $git_hash"
        export branch="ci-update-${git_hash}"
        git checkout -b "${branch}"
        git commit -S -m "${msg}" \
          && git push --set-upstream origin "${branch}" \
          && gh pr create --repo cryostatio/cryostat --base "${{ github.ref_name }}" --title "${msg}" --body 'automatic update' --label chore --reviewer '@cryostatio/maintainers'

  update-console-plugin-submodule:
    if: ${{ github.repository_owner == 'cryostatio' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        repository: cryostatio/cryostat-openshift-console-plugin
        token: "${{ secrets.SUBMODULE_TOKEN }}"
        ref: "${{ github.ref_name }}"
    - name: Check remote cryostat submodule branch
      run: |
        remote_branch="$(git config --get -f .gitmodules submodule."src/cryostat-web".branch)"
        if [[ "$remote_branch" != "${{ github.ref_name }}" ]]; then
          printf "Expected remote branch %s, found branch %s\n" "${{ github.ref_name }}" "$remote_branch" >&2
          exit 1
        fi
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Update submodule to latest commit
      run: |
        git submodule update --init
        git submodule update --remote
    - name: Commit and push submodule
      run: |
        git add --all
        git_hash="$(git rev-parse --short :src/cryostat-web)"
        export msg="build(webui): update submodule to $git_hash"
        export branch="ci-update-${git_hash}"
        git checkout -b "${branch}"
        git commit -S -m "${msg}" \
          && git push --set-upstream origin "${branch}" \
          && gh pr create --repo cryostatio/cryostat-openshift-console-plugin --base "${{ github.ref_name }}" --title "${msg}" --body 'automatic update' --label chore --reviewer '@cryostatio/maintainers'
